# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode15.0
language: swift
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -project Example/EzPopup.xcodeproj -scheme EzPopup-Example -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15' ONLY_ACTIVE_ARCH=NO | xcpretty
